# Generated by Django 4.2.3 on 2024-01-05 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
        ('dictionary', '0001_initial'),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('arrangement_number', models.IntegerField(default=0, null=True)),
                ('last_updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('linked', models.BooleanField(default=False)),
                ('info_type', models.CharField(default='word_card', editable=False, max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dictionary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.word')),
                ('label_linked', models.ManyToManyField(blank=True, to='alerts.label')),
                ('lesson', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
                ('note_linked', models.ManyToManyField(blank=True, to='alerts.note')),
                ('popup_linked', models.ManyToManyField(blank=True, to='alerts.popup')),
            ],
        ),
    ]
