# Generated by Django 4.2.3 on 2023-07-15 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_alter_course_last_updated_alter_lesson_last_updated'),
        ('dictionary', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WordCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('arrangement_number', models.IntegerField(default=0, null=True)),
                ('last_updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dictionary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dictionary.word')),
                ('lesson', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='course.lesson')),
            ],
        ),
    ]
