# Generated by Django 4.2.3 on 2023-07-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordcard',
            name='linked',
            field=models.BooleanField(default=False),
        ),
    ]
