# Generated by Django 4.2.3 on 2023-09-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('word_card', '0002_wordcard_linked'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordcard',
            name='label_linked',
            field=models.ManyToManyField(blank=True, to='alerts.label'),
        ),
        migrations.AddField(
            model_name='wordcard',
            name='note_linked',
            field=models.ManyToManyField(blank=True, to='alerts.note'),
        ),
        migrations.AddField(
            model_name='wordcard',
            name='popup_linked',
            field=models.ManyToManyField(blank=True, to='alerts.popup'),
        ),
    ]
