# Generated by Django 4.2.3 on 2023-09-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_card', '0003_wordcard_label_linked_wordcard_note_linked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordcard',
            name='info_type',
            field=models.CharField(default='word_card', editable=False, max_length=100),
        ),
    ]
