# Generated by Django 4.2.3 on 2023-12-04 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_info_type_lesson_info_type'),
        ('word_card', '0005_alter_wordcard_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordcard',
            name='lesson',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='course.lesson'),
        ),
    ]
