# Generated by Django 4.2.3 on 2024-01-05 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('last_updated', models.DateTimeField(blank=True, editable=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('arrangement_number', models.IntegerField(default=0, null=True)),
                ('info_type', models.CharField(default='course', editable=False, max_length=100)),
                ('arrangements', models.JSONField(blank=True, default={'data': False}, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(blank=True, editable=False)),
                ('arrangement_number', models.IntegerField(default=0, null=True)),
                ('info_type', models.CharField(default='lesson', editable=False, max_length=100)),
                ('arrangement', models.JSONField(blank=True, default=list, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_course', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('word_card', 'word_card'), ('dialogue_group', 'dialogue_group'), ('label', 'label'), ('note', 'note'), ('popup', 'popup')], max_length=20)),
                ('item_id', models.PositiveIntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
            ],
        ),
    ]
