# Generated by Django 4.2.3 on 2023-07-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='last_updated',
            field=models.DateTimeField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='last_updated',
            field=models.DateTimeField(blank=True, editable=False),
        ),
    ]
