# Generated by Django 4.2.3 on 2024-01-07 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_itemlist_dg_object_itemlist_l_object_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemlist',
            name='dg_object',
        ),
        migrations.RemoveField(
            model_name='itemlist',
            name='l_object',
        ),
        migrations.RemoveField(
            model_name='itemlist',
            name='n_object',
        ),
        migrations.RemoveField(
            model_name='itemlist',
            name='pu_object',
        ),
        migrations.RemoveField(
            model_name='itemlist',
            name='wc_object',
        ),
    ]
