# Generated by Django 4.2.3 on 2023-09-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_last_updated_alter_lesson_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='info_type',
            field=models.CharField(default='course', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='lesson',
            name='info_type',
            field=models.CharField(default='lesson', editable=False, max_length=100),
        ),
    ]
