# Generated by Django 4.2.3 on 2023-12-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_lesson_arragements'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='arragements',
            field=models.JSONField(default={'items': []}),
        ),
    ]
