# Generated by Django 4.2.3 on 2024-01-05 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(choices=[('male_voice', 'Male Voice'), ('female_voice', 'Female Voice')], default='male_voice', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='dialogue_voices/')),
                ('meaning', models.CharField(default='', max_length=300)),
                ('ideogram', models.CharField(default='', max_length=300)),
                ('pronunciation', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('arrangement_number', models.IntegerField(default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('info_type', models.CharField(default='balloon', editable=False, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('arrangement_number', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('info_type', models.CharField(default='dialogue', editable=False, max_length=100)),
                ('ballon', models.ManyToManyField(blank=True, to='dialogue.ballon')),
            ],
        ),
        migrations.CreateModel(
            name='DialogueGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('arrangement_number', models.IntegerField(default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('info_type', models.CharField(default='dialogue_group', editable=False, max_length=100)),
                ('arrangement', models.JSONField(blank=True, default=list, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=100)),
                ('answer_type', models.CharField(choices=[('i', 'ideogram type'), ('p', 'Pinyin Type'), ('m', 'Meaning Type')], default='i', max_length=20)),
                ('arrangement_number', models.IntegerField(default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('info_type', models.CharField(default='test_answer', editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('ideogram', 'ideogram'), ('pinyin', 'pinyin')], default='ideogram', max_length=20)),
                ('test_text', models.TextField(blank=True, null=True)),
                ('hide', models.TextField(blank=True, default='', null=True)),
                ('arrangement_number', models.IntegerField(default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('info_type', models.CharField(default='test_card', editable=False, max_length=100)),
                ('answers', models.ManyToManyField(blank=True, to='dialogue.testanswer')),
                ('dialogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dialogue.dialogue')),
                ('dialogue_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dialogue.dialoguegroup')),
                ('edited_ballon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dialogue.ballon')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='testanswer',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dialogue.testcard'),
        ),
        migrations.AddField(
            model_name='testanswer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ImageModal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.ImageField(blank=True, upload_to='dialogue_images/')),
                ('hints', models.CharField(default='', max_length=100)),
                ('arrangement_number', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('info_type', models.CharField(default='image-modal', editable=False, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dialogue',
            name='dialogue_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dialogue.dialoguegroup'),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='image',
            field=models.ManyToManyField(blank=True, to='dialogue.imagemodal'),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.lesson'),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
