# Generated by Django 4.2.3 on 2023-09-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballon',
            name='info_type',
            field=models.CharField(default='balloon', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='dialogue',
            name='info_type',
            field=models.CharField(default='dialogue', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='dialoguegroup',
            name='info_type',
            field=models.CharField(default='dialogue_group', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='imagemodal',
            name='info_type',
            field=models.CharField(default='image-modal', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='testanswer',
            name='info_type',
            field=models.CharField(default='test_answer', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='testcard',
            name='info_type',
            field=models.CharField(default='test_card', editable=False, max_length=100),
        ),
    ]
