# Generated by Django 4.2.3 on 2023-12-07 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0002_ballon_info_type_dialogue_info_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcard',
            name='edited_ballon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dialogue.ballon'),
        ),
    ]
