# Generated by Django 4.2.3 on 2024-01-07 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0002_dgitemlistmain'),
    ]

    operations = [
        migrations.AddField(
            model_name='dgitemlistmain',
            name='d_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dialogue.dialogue'),
        ),
        migrations.AddField(
            model_name='dgitemlistmain',
            name='tc_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dialogue.testcard'),
        ),
    ]
