# Generated by Django 4.2.3 on 2023-12-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0003_testcard_edited_ballon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrangedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('item_type', models.CharField(choices=[('DIALOGUE', 'DIALOGUE'), ('WORD_CARD', 'WORD_CARD'), ('DIALOGUE_GROUP', 'DIALOGUE_GROUP'), ('LESSON', 'LESSON')], default='WORD_CARD', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PageArrangement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(default='')),
                ('arranged_items', models.ManyToManyField(null=True, to='dialogue.arrangeditem')),
            ],
        ),
    ]
