# Generated by Django 4.2.3 on 2023-12-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0005_remove_pagearrangement_arranged_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialoguegroup',
            name='arragement',
            field=models.JSONField(default={'items': []}),
        ),
    ]
