# Generated by Django 4.2.3 on 2023-12-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0006_alter_dialoguegroup_arragement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dialoguegroup',
            name='arragement',
        ),
        migrations.AddField(
            model_name='dialoguegroup',
            name='arragements',
            field=models.JSONField(default={'items': []}),
        ),
    ]
