# Generated by Django 4.2.3 on 2023-12-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0007_remove_dialoguegroup_arragement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialoguegroup',
            name='arragements',
            field=models.JSONField(default={}),
        ),
    ]
