# Generated by Django 4.2.3 on 2023-12-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0008_alter_dialoguegroup_arragements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dialoguegroup',
            name='arragements',
            field=models.JSONField(default={'data': False}),
        ),
    ]
