# Generated by Django 4.2.3 on 2023-09-26 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_last_updated_alter_lesson_last_updated'),
        ('alerts', '0002_popup_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.lesson'),
        ),
    ]
