# Generated by Django 4.2.3 on 2023-09-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_note_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='info_type',
            field=models.CharField(default='label', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='note',
            name='info_type',
            field=models.CharField(default='note', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='popup',
            name='info_type',
            field=models.CharField(default='popup', editable=False, max_length=100),
        ),
    ]
