# Generated by Django 4.2.3 on 2023-09-27 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_info_type_lesson_info_type'),
        ('alerts', '0004_label_info_type_note_info_type_popup_info_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.lesson'),
        ),
    ]
