# Generated by Django 4.2.3 on 2023-07-18 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning', models.CharField(blank=True, max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('ideogram', models.CharField(blank=True, max_length=100)),
                ('pronunciation', models.CharField(blank=True, max_length=100)),
                ('text', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('HSK', models.PositiveIntegerField(blank=True)),
                ('last_updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False)),
                ('arrangement_number', models.IntegerField(default=0, null=True)),
                ('male_voice', models.FileField(blank=True, default=None, null=True, upload_to='audio/male_voices')),
                ('female_voice', models.FileField(blank=True, default=None, null=True, upload_to='audio/female_voices')),
            ],
        ),
    ]
