# Generated by Django 4.2.3 on 2023-09-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='info_type',
            field=models.CharField(default='word', editable=False, max_length=100),
        ),
    ]
