# Generated by Django 4.2.3 on 2023-10-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_hanzi_image_hanzi_meaning_alter_hanzi_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='hanzi',
            name='hsk',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
