# Generated by Django 4.2.3 on 2023-10-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_hanzi_hsk'),
    ]

    operations = [
        migrations.AddField(
            model_name='hanzi',
            name='strokes_no',
            field=models.IntegerField(blank=True, default=3),
        ),
    ]
